config/routes.rb
Rails.application.routes.draw do
  root "boardgames#index"

  resources :boardgames
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boardgame.rb
class Boardgame < ApplicationRecord
  has_one_attached :board
  has_one_attached :instruction
  has_many_attached :pictures

  validates_presence_of :name, :rules, :instruction
  # validate :instructions_in_pdf
  validates :board, presence: true, blob: { content_type: ['image/jpg', 'image/jpeg', 'image/png'] }
  validates :instruction, presence: true, blob: { content_type: 'application/pdf' }
  validates :pictures, presence: true, blob: { content_type: ['image/jpg', 'image/jpeg', 'image/png'] }

  # def instructions_in_pdf
  #   if !instruction.nil? && !instruction.blob.content_type.in?(%('application/pdf'))
  #     errors.add(:instruction, 'must be a pdf file')
  #   end
  # end



end

app/models/concerns/blob_validator.rb
class BlobValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, values)
    return unless values.attached?

    Array(values).each do |value|
      if options[:size_range].present?
        if options[:size_range].min > value.blob.byte_size
          record.errors.add(attribute, :min_size_error, min_size: ActiveSupport::NumberHelper.number_to_human_size(options[:size_range].min))
        elsif options[:size_range].max < value.blob.byte_size
          record.errors.add(attribute, :max_size_error, max_size: ActiveSupport::NumberHelper.number_to_human_size(options[:size_range].max))
        end
      end

      unless valid_content_type?(value.blob)
        record.errors.add(attribute, :content_type)
      end
    end
  end

  private

  def valid_content_type?(blob)
    return true if options[:content_type].nil?

    case options[:content_type]
    when Regexp
      options[:content_type].match?(blob.content_type)
    when Array
      options[:content_type].include?(blob.content_type)
    when Symbol
      blob.public_send("#{options[:content_type]}?")
    else
      options[:content_type] == blob.content_type
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boardgames_controller.rb
class BoardgamesController < ApplicationController
  before_action :set_boardgame, only: %i[ show edit update destroy ]

  # GET /boardgames or /boardgames.json
  def index
    @boardgames = Boardgame.all
  end

  # GET /boardgames/1 or /boardgames/1.json
  def show
  end

  # GET /boardgames/new
  def new
    @boardgame = Boardgame.new
  end

  # GET /boardgames/1/edit
  def edit
  end

  # POST /boardgames or /boardgames.json
  def create
    @boardgame = Boardgame.new(boardgame_params)

    respond_to do |format|
      if @boardgame.save
        format.html { redirect_to boardgame_url(@boardgame), notice: "Boardgame was successfully created." }
        format.json { render :show, status: :created, location: @boardgame }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @boardgame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boardgames/1 or /boardgames/1.json
  def update
    respond_to do |format|
      if @boardgame.update(boardgame_params)
        format.html { redirect_to boardgame_url(@boardgame), notice: "Boardgame was successfully updated." }
        format.json { render :show, status: :ok, location: @boardgame }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @boardgame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boardgames/1 or /boardgames/1.json
  def destroy
    @boardgame.destroy

    respond_to do |format|
      format.html { redirect_to boardgames_url, notice: "Boardgame was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boardgame
      @boardgame = Boardgame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def boardgame_params
      params.require(:boardgame).permit(:name, :rules, :board, :instruction, pictures: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boardgames_helper.rb
module BoardgamesHelper
end

app/views/boardgames/_form.html.erb
<%= form_with(model: boardgame) do |form| %>
  <% if boardgame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boardgame.errors.count, "error") %> prohibited this boardgame from being saved:</h2>

      <ul>
        <% boardgame.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rules %>
    <%= form.text_area :rules %>
  </div>

  <div class="field">
    <%= form.label :instruction, "Instructions" %>
    <%= form.file_field :instruction %>
  </div>

  <div class="field">
    <%= form.label :board, "Board Picture" %>
    <%= form.file_field :board %>
  </div>
  
  <div class="field">
    <%= form.label :pictures %>
    <%= form.file_field :pictures, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boardgames/edit.html.erb
<h1>Editing Boardgame</h1>

<%= render 'form', boardgame: @boardgame %>

<%= link_to 'Show', @boardgame %> |
<%= link_to 'Back', boardgames_path %>

app/views/boardgames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boardgames</h1>

<table>
  <thead>
    <tr>
      <th>Board</th>
      <th>Name</th>
      <th>Rules</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boardgames.each do |boardgame| %>
      <tr>
        <td><%= image_tag boardgame.board.variant(resize: "100x100", colorspace: "Gray").processed %></td>
        <td><%= boardgame.name %></td>
        <td><%= boardgame.rules %></td>
        <td><%= link_to 'Show', boardgame %></td>
        <td><%= link_to 'Edit', edit_boardgame_path(boardgame) %></td>
        <td><%= link_to 'Destroy', boardgame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boardgame', new_boardgame_path %>

app/views/boardgames/new.html.erb
<h1>New Boardgame</h1>

<%= render 'form', boardgame: @boardgame %>

<%= link_to 'Back', boardgames_path %>

app/views/boardgames/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Name:</strong>
  <%= @boardgame.name %>
</h1>

<h3>Board</h3>
<%= image_tag @boardgame.board.variant(resize: "100x100", colorspace: "Gray").processed %>
<%= link_to "Download", rails_blob_path(@boardgame.board, disposition: "attachment") %>

<h3>Game Images</h3>
<% @boardgame.pictures.each do |pic| %>
  <div>
    <%= image_tag pic.variant(resize: "100x100", colorspace: "Gray").processed %>
    <%= link_to "Download", rails_blob_path(pic, disposition: "attachment") %>
  </div>
<% end %>

<h3>Rules</h3>
  <%= link_to "Download Rules", rails_blob_path(@boardgame.instruction, disposition: "attachment") %>

<p>
  <strong>Rules:</strong>
  <%= @boardgame.rules %>
</p>

<%= link_to 'Edit', edit_boardgame_path(@boardgame) %> |
<%= link_to 'Back', boardgames_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boardgames</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>